version: "3.2"
services:
  db:
    container_name: mysqldb
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  php:
    container_name: php
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
volumes:
  db_data:
